### ISSUE TITLE
Autoupdate problem

### ISSUE THREAD

**Issue by zmata** [mschlenstedt/LoxBerry-Plugin-LMS4Lox#2]
There is problem in prerelease.cfg so autoupdate is not working:

VERSION=0.0.0
ARCHIVEURL=https://github.com/mschlenstedt/LoxBerry-Plugin-SamplePlugin-V2-Perl/archive/prerelease_1.0.2.zip
INFOURL=https://github.com/mschlenstedt/LoxBerry-Plugin-SamplePlugin-V2-Perl/commits0

**Comment by mschlenstedt** [comment]
Fixed - thanks. I added the new release to release.cfg (forgot that yesterday).
